### ISSUE TITLE
How to show tablet device?

### ISSUE THREAD

**Issue by vysakh0** [dabbott/javascript-playgrounds#14]
I wanted to see the output for a tablet. So, I tried changing the width(in the url) as given in the docs to
`"//cdn.rawgit.com/dabbott/react-native-web-player/gh-v1.2.4/index.html#width=768&device=android"`

But it doesn't produce tablet like device, more like a bigger phone result. https://output.jsbin.com/veyomoleha Wondering how to go about it. Thanks for the project, would appreciate any help.

**Comment by dabbott** [comment]
I didn't add any tablet images, but happy to accept a PR.

Phone images and sizes are shamelessly ripped from the (MIT licensed) library Framer.js: https://github.com/koenbok/Framer/blob/master/framer/Components/DeviceComponent.coffee

And you can add them here in the web player code: https://github.com/dabbott/react-native-web-player/blob/master/constants/Phones.js

**Comment by dabbott** [comment]
Closing, as I haven't seen any other interest for tablet images. Still happy to accept a PR though.

**Comment by merbin2012** [comment]
@dabbott  How can I remove the image, I want to show the output without any image frame. Just I want to show plain output.
