### ISSUE TITLE
react native web player with zip file?

### ISSUE THREAD

**Issue by jakekwak** [dabbott/javascript-playgrounds#18]
How about supporting the JSZip? (https://stuk.github.io/jszip/ ) The zip file include the everything like same as the real file.

**Comment by dabbott** [comment]
Hmm... what would the workflow look like for running a zip in the web player?

**Comment by dabbott** [comment]
I'm going to close this for now. Happy to reopen if there's still interest. 

I might end up using zips for another similar project. If so, I'll add to this one also.
