### ISSUE TITLE
Using the simualtor for Node Js

### ISSUE THREAD

**Issue by peterjwlee** [dabbott/javascript-playgrounds#23]
Hello, I was reading the ReadMe and got pretty lost. I have react native components (.jsx and .js). I want to generate urls so I can put them in the iframes. I am a little lost in how to do this programmatically in node js. How do you generate the urls for each react native component file? Where do I json encode and URI encode the array files and where does that go? A little clarification would be awesome. Thank you.

**Comment by dabbott** [comment]
The encoded stuff goes after the hash in the URL that you use as the `iframe`'s `src`, e.g. https://cdn.rawgit.com/dabbott/react-native-web-player/gh-v1.10.0/index.html#platform=android

It's a little complicated... maybe one day I'll make a simpler API
