### ISSUE TITLE
custom npm packages in web player

### ISSUE THREAD

**Issue by ahaubenstock** [dabbott/javascript-playgrounds#24]
Hello!

I am having trouble getting the web player to display pages that make use of custom UI elements coming from npm packages.
For example: how might I go about using something like [Native Base](https://nativebase.io) in the web player?

Thanks!

**Comment by andrespch** [comment]
hey @ahaubenstock  did you ever find out more about this?

**Comment by ahaubenstock** [comment]
Not really. I stopped trying, quit my job

**Comment by dabbott** [comment]
I remember trying to get nativebase to work at some point and struggling a bit. This gist is, most RN libs have to be compiled in a form that works with https://github.com/necolas/react-native-web. If it works there, it should work here -- but you'll have to use a version that's bundled in a single file. Instructions for including modules are in the README
