### ISSUE TITLE
How to hide the code area?

### ISSUE THREAD

**Issue by merbin2012** [dabbott/javascript-playgrounds#33]
I will only show the output area inside the <iframe> how can I hide the code area, is any query string available?

**Comment by jasongaare** [comment]
See the `panes` property. Something like this:

let playerOnly = `&panes=${encodeURIComponent(JSON.stringify(['player']))}`;

**Comment by merbin2012** [comment]
@jasongaare Thank you very much. May I ask another one question.
Can I hide the mobile frame? Just I want to show the exact output only.

**Comment by jasongaare** [comment]
I believe if you set the param "platform" to "web" that should accomplish what you are looking for!

**Comment by merbin2012** [comment]
@jasongaree Thank you,  I have plan to create own editor.

**Comment by merbin2012** [comment]
@jasongaree Thank you,  I have plan to create own editor.
