### ISSUE TITLE
Support for FlatList

### ISSUE THREAD

**Issue by sabativi** [dabbott/javascript-playgrounds#37]
Hey,

When I try to run an example with a FlatList component, it renders nothing.
However, react-native-web has support for FlatList, so I am wondering what is missing to make it works.

I will be happy to make a PR.

**Comment by dabbott** [comment]
I think react, react-dom, and react-native-web would need to be upgraded to the latest. I'm happy to review a PR, although it might take me a little while to review since there's actually a lot to test. I use _most_ react-native-web components and need to test a lot of different scenarios.

**Comment by dabbott** [comment]
This works now.
