### ISSUE TITLE
RawGit has been deprecated

### ISSUE THREAD

**Issue by charpeni** [dabbott/javascript-playgrounds#39]
Following this blog post: https://rawgit.com/#19410754303789723334

> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
>
>GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
>
>If you're currently using RawGit, please stop using it as soon as you can.

**Comment by dabbott** [comment]
Fixed!
