### ISSUE TITLE
Add native-base library

### ISSUE THREAD

**Issue by jr-k** [dabbott/javascript-playgrounds#6]
Is it possible to add native-base library in the editor ?

**Comment by dabbott** [comment]
Yeah, we could definitely do that. Maybe something like.. the url params of the iframe allow a `libraries` array. And this could be used to fetch a js bundle.

Probably would need to make a custom build of the native base components, since it has a few native module dependencies.

**Comment by dabbott** [comment]
Ok, so we now can load 3rd party libraries. Will probably still need to make a special build of NativeBase without native dependencies.

If somebody does this, let's definitely include a link to the bundle in the readme.

**Comment by RangerMauve** [comment]
I [raised an issue](https://github.com/GeekyAnts/NativeBase/issues/120) with NativeBase to see if they would consider integrating with react-native-web directly.

**Comment by dabbott** [comment]
That'd be really cool. I'd definitely enjoy using that.

**Comment by dabbott** [comment]
Closing. Any library bundled for browser/commonjs should work in the web player now.
